mail:
    host: mail.jei.com
    port: 587
    username: sayhyerim
    password: fladl1215!
    
board:
    https:
        url: https://devssl.ssro.com/jeislc/controller/loginchk_local.php
        
multipart:
    maxFileSize: 2048KB
    maxRequestSize: 10240KB
    
uploadpath:
        boards: C:\upload\ssrolc\boards
        prmedia: C:\upload\ssrolc\prmedia
        
spring:
    resources:
        cache-period:31556926
        
openapi:
    post:
        key: 0/zvGsrVGa3CSDZ5Qh5rgGpvKY9EhggvoF1kUpGYDhkrzRZqpHN02OSmtZ4USCEiWA1ciJKHUSj8ybpzzfobeQ==
        url: http://openapi.epost.go.kr/postal/retrieveNewAdressAreaCdSearchAllService/retrieveNewAdressAreaCdSearchAllService/getNewAddressListAreaCdSearchAll?ServiceKey={serviceKey}&countPerPage={pageBlockSize}&currentPage={pageNum}&srchwrd={srchwrd}
---
spring.profiles: develop

mail:
    host: mail.jei.com
    port: 587
    username: sayhyerim
    password: fladl1215!
    
board:
    https:
        url: https://devssl.ssro.com/jeislc/controller/loginchk_develop.php
        
multipart:
    maxFileSize: 2048KB
    maxRequestSize: 10240KB
    
uploadpath:
        boards: /home/upload/ssrolc/boards
        prmedia: /home/upload/ssrolc/prmedia
        
spring:
    resources:
        cache-period:31556926
        
openapi:
    post:
        key: 0/zvGsrVGa3CSDZ5Qh5rgGpvKY9EhggvoF1kUpGYDhkrzRZqpHN02OSmtZ4USCEiWA1ciJKHUSj8ybpzzfobeQ==
        url: http://openapi.epost.go.kr/postal/retrieveNewAdressAreaCdSearchAllService/retrieveNewAdressAreaCdSearchAllService/getNewAddressListAreaCdSearchAll?ServiceKey={serviceKey}&countPerPage={pageBlockSize}&currentPage={pageNum}&srchwrd={srchwrd}
---
spring.profiles: product

mail:
    host: mail.jei.com
    port: 587
    username: sayhyerim
    password: fladl1215!
    
board:
    https:
        url: https://devssl.ssro.com/jeislc/controller/loginchk_product.php
        
multipart:
    maxFileSize: 2048KB
    maxRequestSize: 10240KB

uploadpath:
        boards: /home/upload/ssrolc/boards
        prmedia: /home/upload/ssrolc/prmedia

spring:
    resources:
        cache-period:31556926
        
openapi:
    post:
        key: 0/zvGsrVGa3CSDZ5Qh5rgGpvKY9EhggvoF1kUpGYDhkrzRZqpHN02OSmtZ4USCEiWA1ciJKHUSj8ybpzzfobeQ==
        url: http://openapi.epost.go.kr/postal/retrieveNewAdressAreaCdSearchAllService/retrieveNewAdressAreaCdSearchAllService/getNewAddressListAreaCdSearchAll?ServiceKey={serviceKey}&countPerPage={pageBlockSize}&currentPage={pageNum}&srchwrd={srchwrd}
