mail:
    host: mail.jei.com
    port: 587
    username: sayhyerim
    password: fladl1215!
    
board:
    https:
        url: https://devssl.ssro.com/jeislc/controller/loginchk_default.php
---
spring.profiles: develop

mail:
    host: mail.jei.com
    port: 587
    username: sayhyerim
    password: fladl1215!
    
board:
    https:
        url: https://devssl.ssro.com/jeislc/controller/loginchk_develop.php
---
spring.profiles: product

mail:
    host: mail.jei.com
    port: 587
    username: sayhyerim
    password: fladl1215!
    
board:
    https:
        url: https://devssl.ssro.com/jeislc/controller/loginchk_product.php